language: node_js
node_js:
  - '8'
services:
  - docker
script: npm test
notifications:
  slack:
    secure: AcFhcA36J9GyLbqCe9FtcAx9c7NhEnrlwcS4WwKTiJN5UgYRUHDiKdpKGnT3aA1Bjxnl7w4HkY02SwA9bhbTYqIMCiDGcZbNmdi1tpCHmUMB+ASPg8yo3T7R3uA523TkOAdVJNzPwTcS/KPktJ7oPBF1HyidMC/X8VcjbbYgILDcjHdc0sR+PQX3IvoWpCv48wJnF+AeXbpffOoalSsxIBTg87WS5HoQ9dF3aD+poYrHjz0Hoauth4nNKSbexE2fb7N7gbdynCWjcNXCULe9iX3N1pml17laRbgeSshzOyvlXo4sCux9DoXbGML4lqCpT+LGsQWPmM+rsXFAEiHMDuhPfwVIM6LZd3xGW02AA03FbK5kQ+6KirtL5Wv2UTmgzGAKq1qwqKlh3s1zz/SM1Xtya2zuMyPsApXUWRCq94KHMOSaWNFdyM4WyuJs8c2DAPI0+hScjmaTZFFk8TF5XwhCTlqJp3mrrAYO0Bedn8DfKaLnPjotVO+x12QqfxmCvgb/BJndtHlqxA3mr/RWC4KgQmYBIKAgnpzXTrfi78dF4F4vfdKFHmjfG26cO5QjCErgd3GgGptiXxopzxTgMxoaWH7ZrUy6muea79ZKSrVljkaoMraCufBMJIkGaobCfw6Zw2QmTzPpkHpzbFJZjUrBS7UJBq8GY1sPg0gXHbY=
